blog/urls.py
from django.urls import path

from blog.views import ArticlePreview, ArticleView, BlogView, TagsListView, TagView

app_name = "blog"
urlpatterns = [
    path(
        "",
        BlogView.as_view(template_name="blog/home.html"),
        name="home",
    ),
    path(
        "page/<int:page>", BlogView.as_view(template_name="blog/home.html"), name="home"
    ),
    path(
        "tags",
        TagsListView.as_view(template_name="blog/tagslist.html"),
        name="tagslist",
    ),
    path(
        "<slug:slug>",
        ArticleView.as_view(template_name="blog/article.html"),
        name="article",
    ),
    path(
        "tag/<slug:slug>",
        TagView.as_view(template_name="blog/tag.html"),
        name="tag",
    ),
    path(
        "tag/<slug:slug>/page/<int:page>",
        TagView.as_view(template_name="blog/tag.html"),
        name="tag",
    ),
    path(
        "preview/<slug:slug>",
        ArticlePreview.as_view(template_name="blog/article.html"),
        name="preview",
    ),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from tinymce.models import HTMLField

from blog.utils import date_ymd, published_date


User = get_user_model()


class ArticleManager(models.Manager):

    def published(self):
        """Return published articles"""
        return self.filter(status="p")


class Tag(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name="Slug/URL",
    )
    position = models.IntegerField(unique=True, verbose_name="Position")
    meta_description = models.CharField(
        max_length=200,
        blank=True,
        verbose_name="Meta description tag",
    )
    keywords = models.CharField(
        max_length=160,
        blank=True,
        verbose_name="Meta keywords tag",
    )
    robots = models.CharField(
        max_length=60,
        blank=True,
        verbose_name="Meta robots tag",
    )
    
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"
        ordering = ["position"]

    def __str__(self):
        return self.title

    def posts_count(self):
        """Count number of posts for a tag"""
        return Article.objects.filter(tag=self, status="p").count()


class Article(models.Model):
    STATUS_CHOICES = [
        ("d", "Draft"),
        ("p", "Published"),
    ]
    LANGUAGE_CHOICES = [
        ("en", "English"),
        ("fa", "Persian"),
    ]
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        related_name="articles",
        verbose_name="Author",
    )
    title = models.CharField(max_length=250, verbose_name="Title")
    slug = models.SlugField(
        max_length=150,
        unique=True,
        verbose_name="Slug/URL",
    )
    tag = models.ManyToManyField(
        Tag,
        related_name="articles",
        verbose_name="Tag",
    )
    subheading = models.CharField(
        max_length=250,
        blank=True,
        verbose_name="Subheading",
    )
    content = HTMLField(verbose_name="Content")
    published = models.DateField(
        default=timezone.now,
        verbose_name="Published on",
    )
    created = models.DateField(
        auto_now_add=True,
        verbose_name="Created on",
    )
    updated = models.DateField(auto_now=True, verbose_name="Updated on")
    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        verbose_name="Status",
    )
    language = models.CharField(
        max_length=2,
        choices=LANGUAGE_CHOICES,
        verbose_name="Language",
    )
    meta_description = models.CharField(
        max_length=160,
        blank=True,
        verbose_name="Meta description tag",
    )
    keywords = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="Meta keywords tag",
    )
    robots = models.CharField(
        max_length=60,
        blank=True,
        verbose_name="Meta robots tag",
    )

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"
        ordering = ["-published"]

    def __str__(self):
        return self.title

    def published_modified(self):
        """return published date as Today,or x days before or year-month-day"""
        published = published_date(self.published)
        return published

    def published_ymd(self):
        """return published date as year-month-day"""
        return date_ymd(self.published)

    def create_ymd(self):
        """return create date as year-month-day"""
        return date_ymd(self.created)

    def update_ymd(self):
        """return update/modified date as year-month-day"""
        return date_ymd(self.updated)

    def article_tags(self):
        """Get all tags for an article"""
        return ",\n".join([p.title for p in self.tag.all()])

    objects = ArticleManager()


class BlogConfig(models.Model):
    blog_name = models.CharField(
        max_length=50,
        verbose_name="Title in menu bar",
        default="Blog Name",
    )
    blog_title = models.CharField(
        max_length=70,
        verbose_name="Title in blog main page",
        default="Blog Title",
    )
    blog_subtitle = models.CharField(
        max_length=150,
        blank=True,
        verbose_name="Sub-title in blog main page",
    )

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from resume.mixins import GlobalContextMixin

from blog.models import Article, BlogConfig, Tag


class BlogView(GlobalContextMixin, ListView):
    """View for blog main page, list of all articles"""

    queryset = Article.objects.published()
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["blog_settings"] = BlogConfig.objects.first()

        return context


class ArticleView(GlobalContextMixin, DetailView):
    """View for an article"""

    def get_object(self):
        slug = self.kwargs.get("slug")
        article = get_object_or_404(Article.objects.published(), slug=slug)

        return article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["blog_settings"] = BlogConfig.objects.first()

        return context


class TagView(GlobalContextMixin, ListView):
    """View for tag page, list of articles for a tag"""

    paginate_by = 5

    def get_queryset(self):
        global tag
        slug = self.kwargs.get("slug")
        tag = get_object_or_404(Tag.objects.all(), slug=slug)

        return tag.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["tag"] = tag
        context["blog_settings"] = BlogConfig.objects.first()

        return context


class TagsListView(GlobalContextMixin, ListView):
    """View for all tags list"""

    model = Tag

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["blog_settings"] = BlogConfig.objects.first()

        return context


class ArticlePreview(LoginRequiredMixin, GlobalContextMixin, DetailView):
    """Preview an article before publishing just for admins"""

    def get_object(self):
        slug = self.kwargs.get("slug")
        article = get_object_or_404(Article, slug=slug)
        return article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["blog_settings"] = BlogConfig.objects.first()

        return context

templates/blog/article.html
{% extends 'blog/base.html' %}
{% load static %}

{% block meta_tags %}
    <meta name="description" content="{{ object.meta_description }}" />
    <meta name="author" content="{{ object.author.name }}" />
    <meta name="keywords" content="{{ object.keywords }}">
    <meta name="robots" content="{{ object.robots }}">
    <meta property="og:title" content="{{ object.title }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    <meta property='article:author' content="{{ object.author.name }}" />
    <meta property='article:published_time' content="{{ object.published_ymd }}" />
    <meta property='article:modified_time' content="{{ object.update_ymd }}" />
    <meta property='article:tag' content="{{ object.keywords }}" />
    <meta property="og:description" content="{{ object.meta_description }}" />
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="{{ object.title }}"/>
    <meta name="twitter:description" content="{{ object.meta_description }}"/>
    <meta name="twitter:site" content="@{{ configurations.xcom_user }}"/>
    <meta name="twitter:creator" content="@{{ configurations.xcom_user }}"/>
    <!-- still no meta twitter:image, og:image, schema:image -->
    <script type="application/ld+json">
        {
            "@context": "https://schema.org/",
            "@type": "Article",
            "headline": "{{ object.title }}",
            "alternativeHeadline": "{{ object.subheading }}",
            "author" : {
                "@type" : "Person",
                "name" : "{{ object.author.name }}"
            },
            "genre": "{{object.tag.first}}",
            "keywords": "{{ object.keywords }}",
            "url": "{{ request.build_absolute_uri }}",
            "datePublished": "{{ object.published_ymd }}",
            "dateCreated": "{{ object.create_ymd }}",
            "dateModified": "{{ object.update_ymd }}",
            "description": "{{ object.meta_description }}",
            "articleBody": "{{ object.content|striptags|truncatewords:30 }}"
        }
    </script>
{% endblock meta_tags %}

{% block title %} | {{ object.title }}{% endblock title %}

{% block header %}
    <!-- Page Header-->
    <header>
        <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
            <div class="px-0">
                {% if object.language == 'en' %}
                    <div class="post-heading">
                {% else %}
                    <div class="post-heading vazir-font" dir="rtl">
                {% endif %}
                        <h1 class="text-center">{{ object.title }}</h1>
                        <h2 class="subheading text-center">{{ object.subheading }}</h2>
                        <p class="mt-3 text-center" dir="ltr">
                            By {{ object.author.first_name }} {{ object.author.last_name }}, {{ object.published_modified }}
                            </br>
                            {% for tag in object.tag.all %}
                                <a href="{% url 'blog:tag' tag.slug %}">&nbsp#{{tag.title}}</a>
                            {% endfor %}
                        </p>
                    </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block main %}
    <!-- Post Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                {% if object.language == 'en' %}
                <div class="col-md-10 col-lg-8 col-xl-7">
                {% else %}
                <div class="col-md-10 col-lg-8 col-xl-7 vazir-font">
                {% endif %}
                    {{object.content|safe}}
                </div>
            </div>
        </div>
    </article>
{% endblock main %}

templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ configurations.google_analytics }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '{{ configurations.google_analytics }}');
    </script>

    <!-- meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta_tags %}
    {% endblock meta_tags %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="{% static 'resume/base.css' %}">
    <link rel="stylesheet" href="{% static 'blog/base.css' %}">

    <link rel="icon" type="image/png" href="{{ HTTP_HOST }}{{ configurations.favicon.url }}"/>

    <title>{{ blog_settings.blog_name }}{% block title %}{% endblock title %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand vazir-font" href="{% url 'blog:home' %}">{{ blog_settings.blog_name }}</a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsSite" aria-controls="navbarsSite" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="navbar-collapse collapse" id="navbarsSite">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'resume' %}">About</a></li>
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:tagslist' %}">Tags</a></li>
          </ul>
          <button
          type="button"
          class="btn btn-dark"
          data-theme-toggle>
            <i id="icon-sun-moon" class="bi bi-sun-fill"></i>
          </button>
        </div>
      </div>
    </nav>

    {% block header %}
    {% endblock header %}

    {% block main %}
    {% endblock main %}

    <footer class="text-muted">
        <div class="container text-center aria-hidden="true"">
          <a href="mailto:{{ configurations.email }}" target="_blank"><i class="bi bi-envelope theme social-icons"></i></a>
            <a href="{{ social_accounts.linkedin }}" target="_blank"><i class="bi bi-linkedin theme social-icons"></i></a>
          <p class="theme">{{ configurations.copyright_text }} &copy; {% now "Y" %}</p>
        </div>
    </footer>

    <!-- Back to top button -->
    <button type="button" class="btn btn-secondary btn-floating btn-lg" id="btn-back-to-top">
      <i class="bi bi-arrow-up"></i>
    </button>

    <script src="{% static 'resume/base.js' %}"></script>
    <script src="{% static 'resume/theme-color.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

    {% block footer_script %}
    {% endblock footer_script %}
  </body>

</html>

templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block meta_tags %}
    <meta name="description" content="{{ configurations.description }}" />
    <meta name="author" content="{{ configurations.author }}" />
    <meta name="keywords" content="{{ configurations.keywords }}">
    <meta name="robots" content="{{ configurations.robots }}">
    <meta property="og:title" content="{{ blog_settings.blog_title }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="{{ configurations.description }}" />
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="{{ blog_settings.blog_title }}"/>
    <meta name="twitter:description" content="{{ configurations.description }}"/>
    <meta name="twitter:site" content="@{{ configurations.xcom_user }}"/>
    <meta name="twitter:creator" content="@{{ configurations.xcom_user }}"/>
    <!-- still no meta twitter:image, og:image, schema:image -->
    <script type="application/ld+json">
        {
            "@context": "https://schema.org/",
            "@type": "WebPage",
            "name": "{{ blog_settings.blog_title }}",
            "description": "{{ configurations.description }}",
            "author": {
                "@id": "{{ configurations.author }}"
            },
            "copyrightHolder": {
                "@id": "{{ configurations.author }}"
            },
            "copyrightYear": "{% now "Y-m-d" %}",
            "creator": {
                "@id": "{{ configurations.author }}"
            },
            "publisher": {
                "@id": "{{ configurations.author }}"
            },
            "headline": "{{ blog_settings.blog_title }}",
            "mainEntityOfPage": "{{ request.build_absolute_uri }}",
            "url": "{{ request.build_absolute_uri }}"
        }
    </script>
{% endblock meta_tags %}

{% block header %}
    <!-- Page Header-->
    <header>
        <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
            <div class="px-0">
                <h1 class="display-4 fst-italic text-center">{{ blog_settings.blog_title }}</h1>
                <p class="lead my-3 text-center">{{ blog_settings.blog_subtitle }}</p>
            </div>
        </div>
    </header>
{% endblock header %}

{% block main %}
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for item in object_list %}
                    <!-- Post preview-->
                    {% if item.language == 'en' %}
                        <div class="post-preview">
                    {% else %}
                        <div class="post-preview vazir-font" dir="rtl">
                    {% endif %}
                            <article class="blog-post">
                                <a href="{% url 'blog:article' item.slug %}">
                                    <h2 class="display-5 link-body-emphasis mb-1">{{ item.title }}</h2>
                                </a>
                                <p class="blog-post-meta" dir="ltr">
                                    By {{ item.author.first_name }} {{ item.author.last_name }}, {{ item.published_modified }}
                                    {% for tag in item.tag.all %}
                                        <a href="{% url 'blog:tag' tag.slug %}">&nbsp#{{tag.title}}</a>
                                    {% endfor %}
                                </p>
                                <p>{{ item.content|striptags|truncatewords:20 }}</p>
                                <hr>
                            </article>
                        </div>
                {% endfor %}

                <!-- Pagination -->
                {% if is_paginated %}
                    <nav class="blog-pagination" aria-label="Pagination">
                        {% if page_obj.has_next %}
                            <a class="btn btn-outline-primary rounded-pill" href="{% url 'blog:home' page_obj.next_page_number %}">Older</a>
                        {% endif %}
                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-primary rounded-pill" aria-disabled="true" href="{% url 'blog:home' page_obj.previous_page_number %}">Newer</a>
                        {% endif %}
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock main %}

templates/blog/tag.html
{% extends 'blog/base.html' %}
{% load static %}

{% block meta_tags %}
    <meta name="description" content="{{ tag.meta_description }}" />
    <meta name="author" content="{{ configurations.author }}" />
    <meta name="keywords" content="{{ tag.keywords }}">
    <meta name="robots" content="{{ tag.robots }}">
    <meta property="og:title" content="{{ tag.title }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="{{ tag.meta_description }}" />
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="{{ tag.title }}"/>
    <meta name="twitter:description" content="{{ tag.meta_description }}"/>
    <meta name="twitter:site" content="@{{ configurations.xcom_user }}"/>
    <meta name="twitter:creator" content="@{{ configurations.xcom_user }}"/>
    <!-- still no meta twitter:image, og:image, schema:image -->
    <script type="application/ld+json">
        {
            "@context": "https://schema.org/",
            "@type": "WebPage",
            "name": "{{ tag.title }}",
            "description": "{{ tag.meta_description }}",
            "author": {
                "@id": "{{ configurations.author }}"
            },
            "copyrightHolder": {
                "@id": "{{ configurations.author }}"
            },
            "copyrightYear": "{% now "Y-m-d" %}",
            "creator": {
                "@id": "{{ configurations.author }}"
            },
            "publisher": {
                "@id": "{{ configurations.author }}"
            },
            "headline": "{{ tag.title }}",
            "name": "{{ tag.title }}",
            "mainEntityOfPage": "{{ request.build_absolute_uri }}",
            "url": "{{ request.build_absolute_uri }}"
        }
    </script>
{% endblock meta_tags %}

{% block title %} | #{{ tag.title }}{% endblock title %}

{% block header %}
    <!-- Page Header-->
    <header>
        <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
            <div class="px-0">
                <h1 class="display-4 fst-italic text-center">#{{ tag.title }}</h1>
                <p class="subheading text-center">Articles about {{ tag.title }}</p>
            </div>
        </div>
    </header>
{% endblock header %}
{% block main %}
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for item in object_list %}
                    <!-- Post preview-->
                    {% if item.language == 'en' %}
                        <div class="post-preview">
                    {% else %}
                        <div class="post-preview vazir-font" dir="rtl">
                    {% endif %}
                            <article class="blog-post">
                                <a href="{% url 'blog:article' item.slug %}">
                                    <h2 class="display-5 link-body-emphasis mb-1">{{ item.title }}</h2>
                                </a>
                                <p class="blog-post-meta" dir="ltr">
                                    By {{ item.author.first_name }} {{ item.author.last_name }}, {{ item.published_modified }}
                                    {% for tag in item.tag.all %}
                                        <a href="{% url 'blog:tag' tag.slug %}">&nbsp#{{tag.title}}</a>
                                    {% endfor %}
                                </p>
                                <p>{{ item.content|striptags|truncatewords:20 }}</p>
                                <hr>
                            </article>
                        </div>
                {% endfor %}

                <!-- Pagination -->
                {% if is_paginated %}
                    <nav class="blog-pagination" aria-label="Pagination">
                        {% if page_obj.has_next %}
                            <a class="btn btn-outline-primary rounded-pill" href="{% url 'blog:tag' tag.slug page_obj.next_page_number %}">Older</a>
                        {% endif %}
                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-primary rounded-pill" aria-disabled="true" href="{% url 'blog:tag' tag.slug page_obj.previous_page_number %}">Newer</a>
                        {% endif %}
                    </nav>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock main %}

templates/blog/tagslist.html
{% extends 'blog/base.html' %}
{% load static %}

{% block meta_tags %}
    <meta name="description" content="All categories and tags on {{ blog_settings.blog_title }}" />
    <meta name="author" content="{{ configurations.author }}" />
    <meta name="keywords" content="{% for item in object_list %}{{ item.title }}, {% endfor %}">
    <meta name="robots" content="{{ configurations.robots }}">
    <meta property="og:title" content="{{ blog_settings.blog_title }} Tags" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="All categories and tags on {{ blog_settings.blog_title }}" />
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:title" content="{{ blog_settings.blog_title }} Tags"/>
    <meta name="twitter:description" content="All categories and tags on {{ blog_settings.blog_title }}"/>
    <meta name="twitter:site" content="@{{ configurations.xcom_user }}"/>
    <meta name="twitter:creator" content="@{{ configurations.xcom_user }}"/>
    <!-- still no meta twitter:image, og:image, schema:image -->
    <script type="application/ld+json">
        {
            "@context": "https://schema.org/",
            "@type": "WebPage",
            "name": "{{ blog_settings.blog_title }} Tags",
            "description": "All categories and tags on {{ blog_settings.blog_title }}",
            "author": {
                "@id": "{{ configurations.author }}"
            },
            "copyrightHolder": {
                "@id": "{{ configurations.author }}"
            },
            "copyrightYear": "{% now "Y-m-d" %}",
            "creator": {
                "@id": "{{ configurations.author }}"
            },
            "publisher": {
                "@id": "{{ configurations.author }}"
            },
            "headline": "{{ blog_settings.blog_title }} Tags",
            "name": "{{ blog_settings.blog_title }} Tags",
            "mainEntityOfPage": "{{ request.build_absolute_uri }}",
            "url": "{{ request.build_absolute_uri }}"
        }
    </script>
{% endblock meta_tags %}

{% block title %} | Tags{% endblock title %}

{% block header %}
    <!-- Page Header-->
    <header>
        <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
            <div class="px-0">
                <h1 class="display-4 fst-italic text-center">{{ blog_settings.blog_title }} Tags</h1>
                <p class="subheading text-center">All tags and categories</p>
            </div>
        </div>
    </header>
{% endblock header %}
{% block main %}
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for item in object_list %}
                    <!-- Item preview-->
                    <div class="post-preview">
                        <a href="{% url 'blog:tag' item.slug %}">
                            <h2 class="post-title">#{{ item.title }} ({{ item.posts_count }})</h2>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock main %}